stages:
  - build


build:
  tags: 
    -  testing
  stage: build
  script:
    - docker build -t vmware-filesd:${CI_PIPELINE_ID} -t harbor.compliant.flexentialps.com/fps-public/vmware-filesd:${CI_PIPELINE_ID} .
    - echo $DOCKER_USER
    - echo $DOCKER_PASS
    - echo $DOCKER_PASS | docker login -u$DOCKER_USER --password-stdin harbor.compliant.flexentialps.com
    - docker push harbor.compliant.flexentialps.com/fps-public/vmware-filesd:${CI_PIPELINE_ID} 
